sudo: false
matrix:
  fast_finish: true

language: node_js
node_js:
  - '7'

before_install:
  - 'npm install -g prettier yarn'

install:
  - 'bin/prepare'
  - 'bin/doctor'

script:
  - 'bin/lint'
  - 'bin/test'
