language: node_js
node_js:
  - "7"
env:
  - 'TEST_DIR=packages/eslint-config-samsao-base'
  - 'TEST_DIR=packages/eslint-config-samsao-web'
before_install:
  - 'cd $TEST_DIR'
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then case "$(npm --version)" in 1.*) npm install -g npm@1.4.28 ;; 2.*) npm install -g npm@2 ;; esac ; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.6" ] && [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then npm install -g npm; fi'
script:
  - 'npm run travis'
sudo: false
matrix:
  fast_finish: true
